version: "3"

services:
  version: '3'

services:
  db:
    image: mariadb:5.5
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=CachTime
      - MYSQL_DATABASE=CachTime
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - .:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    build: ./django_cache
    command: bash -c "cd django_cache && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_cache
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:mariadb55
