FROM python:3
ENV PYTHONUNBUFFERED 1
EXPOSE 8001 80 5555
RUN mkdir /django_cache
RUN apt-get update \
    && apt-get install -y \
    memcached=${MEMCACHED_VERSION}*
WORKDIR /django_cache
COPY requirements.txt /django_cache
RUN pip install -r requirements.txt